jobs:
  build:
    working_directory: ~/blockchain
    docker:
      - image: elixir:latest
    steps:
      - run: apt-get update; apt-get -y install libgmp3-dev
      - checkout
      - restore_cache:
          key: _build
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test
      - run: mix dialyzer
      - save_cache:
          key: _build
          paths:
            - _build
